spring.profiles.active: development

environments:
    dev:
        url: http://dev.bar.com
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App
my:
   servers:
       - dev.bar.com
       - foo.bar.com

server:
    port: 9000
---

spring:
    profiles: development
server:
    port: 9000

---

spring:
    profiles: production
server:
    port: 0